version: 2
updates:
  - package-ecosystem: "nuget" # update .NET dependencies
    directory: "/" 
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "FluentAssertions"
        versions:
          - "8.*"

  - package-ecosystem: "github-actions" # update GitHub Actions workflows
    directory: "/" 
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"